#!/usr/bin/python
import signal
from reachstatus import StateClient
from wificontrol import WiFiMonitor
from dev_utils import configure_logging


def main():
    configure_logging()

    def handler(signum, frame):
        wifi_monitor.shutdown()

    wifi_monitor = WiFiMonitor()

    wifi_monitor.register_callback(wifi_monitor.HOST_STATE, StateClient.set_network_host_state)
    wifi_monitor.register_callback(wifi_monitor.CLIENT_STATE, StateClient.set_network_client_state)
    wifi_monitor.register_callback(wifi_monitor.OFF_STATE, StateClient.set_network_disabled_state)
    wifi_monitor.register_callback(wifi_monitor.SCAN_STATE, StateClient.set_network_scan_state)
    wifi_monitor.register_callback(wifi_monitor.REVERT_EVENT,
                                   StateClient.send_revert_connect_notify)
    wifi_monitor.register_callback(wifi_monitor.SUCCESS_EVENT,
                                   StateClient.send_success_connect_notify)

    signal.signal(signal.SIGINT, handler)
    signal.signal(signal.SIGTERM, handler)

    wifi_monitor.run()


if __name__ == '__main__':
    main()
